### ISSUE TITLE
Broken links in episode 2

### ISSUE THREAD

**Issue by jefffor** [aws-samples/aws-cloud-and-hybrid-operations-workshop#10]
Two links have target files with extension yml but the actual target file is .yaml

episode-02-step-01-enable-config-cloudtrail.md links to 
https://github.com/aws-samples/aws-cloud-and-hybrid-operations-workshop/blob/main/cfntemplates/workshop-config-prerequisites.yml

 but the correct link is 
https://github.com/aws-samples/aws-cloud-and-hybrid-operations-workshop/blob/main/cfntemplates/workshop-config-prerequisites.yaml

Similarly for step 3 with 
https://github.com/aws-samples/aws-cloud-and-hybrid-operations-workshop/blob/main/cfntemplates/Operational-Best-Practices-for-Amazon-S3-with-Remediation.yml

should be 

https://github.com/aws-samples/aws-cloud-and-hybrid-operations-workshop/blob/main/cfntemplates/Operational-Best-Practices-for-Amazon-S3-with-Remediation.yaml

**Comment by awserik** [comment]
Thank you @jefffor for the submission and pointing this out! I just updated the links so they should be working now.
